# Generated by Django 3.2.4 on 2021-07-18 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_mycart'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardno', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=4)),
                ('expiry', models.CharField(max_length=10)),
                ('balance', models.FloatField(default=10000)),
            ],
            options={
                'db_table': 'MyAccount',
            },
        ),
        migrations.CreateModel(
            name='OrderMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=1000)),
                ('dateOfOrder', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.userinfo')),
            ],
            options={
                'db_table': 'OrderMaster',
            },
        ),
    ]
