# Generated by Django 3.2.4 on 2021-07-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_myaccount_ordermaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('date_of_order', models.DateField()),
                ('amount', models.FloatField(default=100)),
                ('product_details', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Order_Master',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('card_no', models.CharField(max_length=4)),
                ('cvv', models.CharField(max_length=4)),
                ('expiry', models.CharField(max_length=8)),
                ('balance', models.FloatField(default=10000)),
            ],
            options={
                'db_table': 'Payment',
            },
        ),
        migrations.DeleteModel(
            name='MyAccount',
        ),
        migrations.DeleteModel(
            name='OrderMaster',
        ),
    ]
